apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: owncloud-service
  name: owncloud-service
spec: 
  ports:
    - 
      targetPort: 80
      port: 80
  selector: 
    app: owncloud
#  type: LoadBalancer
